### ISSUE TITLE
我在使用ng test的时候有莫名其妙的错误

### ISSUE THREAD

**Issue by AlexYY0** [jerryshell/passwordbox-angular-springboot-front-end#1]
我在使用ng test进行单元测试的时候，有很多错误，但是当我去解决的时候，我发现并没有这个错误。
比如：Can't bind to 'formGroup' since it isn't a known property of 'form'. 这个错误。网上一致的解决方案是：**需要从@angular/forms导入ReactiveFormsModule。因为FormGroupDirective 指令属于ReactiveFormsModule一部分。**但是我十分肯定，原代码里面有ReactiveFormsModule，没有错误，不知道为什么报错。【这个类型的错误很多】
再比如：NullInjectorError: No provider for HttpClient! 这个错误。网上一致的解决方案是：
```
1. 在 app.module.ts 中引入模块
import { HttpClientModule } from '@angular/common/http';
2. 在 @NgModule.imports 中引入它
复制代码
@NgModule({
    ......
    imports: [
        ......
        HttpClientModule,
        ......
    ],
    ......
})
```
我确信原代码里面有这个，依旧报错，同上面。

**Comment by jerryshell** [comment]
我在这里测试没问题，请确认执行 `ng test` 之前你已经执行 `npm install` 安装依赖包。

**Comment by AlexYY0** [comment]
我ng serve运行的时候，好像没什么问题。但是ng test就有上面的问题。
执行了`npm install`，但是因为我是Windows操作系统，所以安不了fsevents，这是mac上的，没什么影响。
![1](https://user-images.githubusercontent.com/32156135/54748239-05139a00-4c0c-11e9-8b55-58160163dcea.PNG)

![2](https://user-images.githubusercontent.com/32156135/54748182-e31a1780-4c0b-11e9-97a1-36a2975ac91d.PNG)
于是debug，打开http://localhost:9876/
![3](https://user-images.githubusercontent.com/32156135/54748363-6176b980-4c0c-11e9-9499-1dfe29fa7fa5.PNG)
于是细看错误
![4](https://user-images.githubusercontent.com/32156135/54748372-6a678b00-4c0c-11e9-8f0a-45cd7de7c5c5.PNG)

**Comment by jerryshell** [comment]
`ng serve` 正常就行。说实话 `ng test` 我也没用过。所以这个项目的单元测试我还没写，好像不改默认的单元测试的文件就会出现这种错误，我在网上看到了[类似的情况](http://www.cnblogs.com/cgzl/p/8615357.html)。

**Comment by AlexYY0** [comment]
好吧，我只能再看看了，你自己ng test也是这样吗？

**Comment by jerryshell** [comment]
在我的电脑上是一片空白，换其他电脑之后复现了你的问题。
